application:
  port: 8000
  
database:
  host: "127.0.0.1"
  port: 49154
  username: "postgres"
  password: "postgrespw"
  database_name: "newsletter"

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "05973954-6847-4b63-bf9b-7c7c345d959b"
  timeout_milliseconds: 10000
  